# Generated by Django 3.0.2 on 2020-02-27 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('uuid', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=3000)),
                ('first_coefficient', models.DecimalField(decimal_places=2, max_digits=2)),
                ('second_coefficient', models.DecimalField(decimal_places=2, max_digits=2)),
                ('third_coefficient', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserBets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_much_bet_user', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bet_date', models.DateTimeField()),
                ('bet', models.ManyToManyField(to='bet.Bets')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.BetCategories')),
            ],
        ),
        migrations.AddField(
            model_name='bets',
            name='game',
            field=models.ManyToManyField(to='bet.Game'),
        ),
    ]
