# Generated by Django 3.0.3 on 2020-03-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('uuid', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=2)),
                ('coeff_start_date', models.DateTimeField(auto_now_add=True)),
                ('coeff_until_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bet_money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bet_date', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bet.Bets')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.BetCategories')),
            ],
        ),
        migrations.AddField(
            model_name='bets',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bet.Coefficients'),
        ),
        migrations.AddField(
            model_name='bets',
            name='game',
            field=models.ManyToManyField(to='bet.Game'),
        ),
    ]
